name: Update leanpub branches

on:
  push:
    branches:
      - dev
    paths:
      - 'manuscript/*.md'
      - 'manuscript/**/*.md'
      - '.github/workflows/*'

jobs:
  update-leanpub:
    name: update-leanpub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout charts repo
      uses: actions/checkout@v2

    - name: Checkout latest leanpub-preview branch
      uses: actions/checkout@v2
      with:    
        repository: ${{ env.GITHUB_PAGES_REPO }}
        ref: leanpub-preview  
        path: leanpub-preview

    - name: Replace contents of leanpub-preview branch
      run: |
        rm -rf leanpub-preview/manuscript
        cp -rf manuscript leanpub-preview/
        cd leanpub-preview
        ./scripts/markdown-to-markua.sh

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        directory: leanpub-preview
        branch: leanpub-preview